// src/lib/components/LoginForm.svelte
<script>
	import Card from './Card.svelte';
	import Button from './Button.svelte';
	import TextField from './TextField.svelte';
	import Checkbox from './Checkbox.svelte';
	import CircularProgress from './CircularProgress.svelte';
	import { login } from '$lib/api.js';
	import { createEventDispatcher } from 'svelte';

	const dispatch = createEventDispatcher();

	let email = '';
	let password = '';
	let loading = false;
	let error = '';
	let showPassword = false;

	$: canSubmit = email && password && !loading;

	async function handleSubmit() {
		if (!canSubmit) return;

		loading = true;
		error = '';

		try {
			const result = await login(email, password);
			// Store token if needed
			if (result.token) {
				localStorage.setItem('authToken', result.token);
			}
			dispatch('loginSuccess', result);
		} catch (err) {
			error = err.message || 'Login failed. Please check your credentials.';
		} finally {
			loading = false;
		}
	}

	function handleKeyPress(event) {
		if (event.key === 'Enter' && canSubmit) {
			handleSubmit();
		}
	}
</script>

<div class="min-h-screen flex items-center justify-center p-5 bg-gradient-to-br from-white to-gray-50">
	<Card elevation={2} class="w-full max-w-sm p-8">
		<div class="text-center mb-8">
			<h1 class="text-3xl font-medium text-primary-700 mb-2">SIGLAT Admin</h1>
			<p class="text-gray-600">Sign in to your admin account</p>
		</div>

		<form on:submit|preventDefault={handleSubmit} class="space-y-6">
			<TextField
				bind:value={email}
				label="Email"
				type="email"
				required
				fullWidth
				disabled={loading}
				on:keypress={handleKeyPress}
			/>

			<TextField
				bind:value={password}
				label="Password"
				type={showPassword ? 'text' : 'password'}
				required
				fullWidth
				disabled={loading}
				on:keypress={handleKeyPress}
			/>

			<Checkbox
				bind:checked={showPassword}
				disabled={loading}
				label="Show password"
			/>

			{#if error}
				<div class="bg-red-50 border-l-4 border-red-400 p-4 rounded">
					<p class="text-sm text-red-700">{error}</p>
				</div>
			{/if}

			<Button 
				type="submit"
				variant="contained"
				color="primary"
				fullWidth
				disabled={!canSubmit}
				size="large"
			>
				{#if loading}
					<CircularProgress size="small" />
					<span class="ml-2">Signing in...</span>
				{:else}
					Sign In
				{/if}
			</Button>
		</form>
	</Card>
</div>

// src/components/LoginForm.tsx
import React, { useState } from 'react';
import Card from './Card';
import Button from './Button';
import TextField from './TextField';
import Checkbox from './Checkbox';
import CircularProgress from './CircularProgress';

interface LoginFormProps {
  onLoginSuccess?: (result: any) => void;
  title?: string;
  subtitle?: string;
}

const LoginForm: React.FC<LoginFormProps> = ({ 
  onLoginSuccess,
  title = "SIGLAT Admin",
  subtitle = "Sign in to your admin account"
}) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  const canSubmit = email && password && !loading;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!canSubmit) return;

    setLoading(true);
    setError('');

    try {
      // Simulate API call
      const result = { token: 'mock-token', user: { email } };
      localStorage.setItem('authToken', result.token);
      onLoginSuccess?.(result);
    } catch (err: any) {
      setError(err.message || 'Login failed. Please check your credentials.');
    } finally {
      setLoading(false);
    }
  };

  const handleKeyPress = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter' && canSubmit) {
      handleSubmit(event as any);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-5 bg-gradient-to-br from-white to-gray-50">
      <Card elevation={2} className="w-full max-w-sm p-8">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-medium text-primary-700 mb-2">{title}</h1>
          <p className="text-gray-600">{subtitle}</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          <TextField
            value={email}
            onChange={setEmail}
            label="Email"
            type="email"
            required
            fullWidth
            disabled={loading}
            onKeyPress={handleKeyPress}
          />

          <TextField
            value={password}
            onChange={setPassword}
            label="Password"
            type={showPassword ? 'text' : 'password'}
            required
            fullWidth
            disabled={loading}
            onKeyPress={handleKeyPress}
          />

          <Checkbox
            checked={showPassword}
            onChange={setShowPassword}
            disabled={loading}
            label="Show password"
          />

          {error && (
            <div className="bg-red-50 border-l-4 border-red-400 p-4 rounded">
              <p className="text-sm text-red-700">{error}</p>
            </div>
          )}

          <Button 
            type="submit"
            variant="contained"
            color="primary"
            fullWidth
            disabled={!canSubmit}
            size="large"
          >
            {loading ? (
              <>
                <CircularProgress size="small" />
                <span className="ml-2">Signing in...</span>
              </>
            ) : (
              'Sign In'
            )}
          </Button>
        </form>
      </Card>
    </div>
  );
};

export default LoginForm;
